sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t raditr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raditr/react-test npm test -- --coverage

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t raditr/multi-client ./client
  - docker build -t raditr/multi-nginx ./nginx
  - docker build -t raditr/multi-server ./server
  - docker build -t raditr/multi-worker ./worker
  - docker push raditr/multi-client
  - docker push raditr/multi-nginx
  - docker push raditr/multi-server
  - docker push raditr/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-316597545477
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY